<?php

function getALLCountries()
{
    return [
        ['code' => 'AF', 'name' => 'Afghanistan', 'flag' => 'flags/afghanistan.svg'],
        ['code' => 'AX', 'name' => 'Aland Islands', 'flag' => 'flags/aland-islands.svg'],
        ['code' => 'AL', 'name' => 'Albania', 'flag' => 'flags/albania.svg'],
        ['code' => 'DZ', 'name' => 'Algeria', 'flag' => 'flags/algeria.svg'],
        ['code' => 'AS', 'name' => 'American Samoa', 'flag' => 'flags/american-samoa.svg'],
        ['code' => 'AD', 'name' => 'Andorra', 'flag' => 'flags/andorra.svg'],
        ['code' => 'AO', 'name' => 'Angola', 'flag' => 'flags/angola.svg'],
        ['code' => 'AI', 'name' => 'Anguilla', 'flag' => 'flags/anguilla.svg'],
        ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'flag' => 'flags/antigua-and-barbuda.svg'],
        ['code' => 'AR', 'name' => 'Argentina', 'flag' => 'flags/argentina.svg'],
        ['code' => 'AM', 'name' => 'Armenia', 'flag' => 'flags/armenia.svg'],
        ['code' => 'AW', 'name' => 'Aruba', 'flag' => 'flags/aruba.svg'],
        ['code' => 'AU', 'name' => 'Australia', 'flag' => 'flags/australia.svg'],
        ['code' => 'AT', 'name' => 'Austria', 'flag' => 'flags/austria.svg'],
        ['code' => 'AZ', 'name' => 'Azerbaijan', 'flag' => 'flags/azerbaijan.svg'],
        ['code' => 'BS', 'name' => 'Bahamas', 'flag' => 'flags/bahamas.svg'],
        ['code' => 'BH', 'name' => 'Bahrain', 'flag' => 'flags/bahrain.svg'],
        ['code' => 'BD', 'name' => 'Bangladesh', 'flag' => 'flags/bangladesh.svg'],
        ['code' => 'BB', 'name' => 'Barbados', 'flag' => 'flags/barbados.svg'],
        ['code' => 'BY', 'name' => 'Belarus', 'flag' => 'flags/belarus.svg'],
        ['code' => 'BE', 'name' => 'Belgium', 'flag' => 'flags/belgium.svg'],
        ['code' => 'BZ', 'name' => 'Belize', 'flag' => 'flags/belize.svg'],
        ['code' => 'BJ', 'name' => 'Benin', 'flag' => 'flags/benin.svg'],
        ['code' => 'BM', 'name' => 'Bermuda', 'flag' => 'flags/bermuda.svg'],
        ['code' => 'BT', 'name' => 'Bhutan', 'flag' => 'flags/bhutan.svg'],
        ['code' => 'BO', 'name' => 'Bolivia, Plurinational State of', 'flag' => 'flags/bolivia.svg'],
        ['code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba', 'flag' => 'flags/bonaire.svg'],
        ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'flag' => 'flags/bosnia-and-herzegovina.svg'],
        ['code' => 'BW', 'name' => 'Botswana', 'flag' => 'flags/botswana.svg'],
        ['code' => 'BR', 'name' => 'Brazil', 'flag' => 'flags/brazil.svg'],
        ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'flag' => 'flags/british-indian-ocean-territory.svg'],
        ['code' => 'BN', 'name' => 'Brunei Darussalam', 'flag' => 'flags/brunei.svg'],
        ['code' => 'BG', 'name' => 'Bulgaria', 'flag' => 'flags/bulgaria.svg'],
        ['code' => 'BF', 'name' => 'Burkina Faso', 'flag' => 'flags/burkina-faso.svg'],
        ['code' => 'BI', 'name' => 'Burundi', 'flag' => 'flags/burundi.svg'],
        ['code' => 'KH', 'name' => 'Cambodia', 'flag' => 'flags/cambodia.svg'],
        ['code' => 'CM', 'name' => 'Cameroon', 'flag' => 'flags/cameroon.svg'],
        ['code' => 'CA', 'name' => 'Canada', 'flag' => 'flags/canada.svg'],
        ['code' => 'CV', 'name' => 'Cape Verde', 'flag' => 'flags/cape-verde.svg'],
        ['code' => 'KY', 'name' => 'Cayman Islands', 'flag' => 'flags/cayman-islands.svg'],
        ['code' => 'CF', 'name' => 'Central African Republic', 'flag' => 'flags/central-african-republic.svg'],
        ['code' => 'TD', 'name' => 'Chad', 'flag' => 'flags/chad.svg'],
        ['code' => 'CL', 'name' => 'Chile', 'flag' => 'flags/chile.svg'],
        ['code' => 'CN', 'name' => 'China', 'flag' => 'flags/china.svg'],
        ['code' => 'CX', 'name' => 'Christmas Island', 'flag' => 'flags/christmas-island.svg'],
        ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'flag' => 'flags/cocos-island.svg'],
        ['code' => 'CO', 'name' => 'Colombia', 'flag' => 'flags/colombia.svg'],
        ['code' => 'KM', 'name' => 'Comoros', 'flag' => 'flags/comoros.svg'],
        ['code' => 'CK', 'name' => 'Cook Islands', 'flag' => 'flags/cook-islands.svg'],
        ['code' => 'CR', 'name' => 'Costa Rica', 'flag' => 'flags/costa-rica.svg'],
        ['code' => 'CI', 'name' => "Côte d'Ivoire", 'flag' => 'flags/ivory-coast.svg'],
        ['code' => 'HR', 'name' => 'Croatia', 'flag' => 'flags/croatia.svg'],
        ['code' => 'CU', 'name' => 'Cuba', 'flag' => 'flags/cuba.svg'],
        ['code' => 'CW', 'name' => 'Curaçao', 'flag' => 'flags/curacao.svg'],
        ['code' => 'CZ', 'name' => 'Czech Republic', 'flag' => 'flags/czech-republic.svg'],
        ['code' => 'DK', 'name' => 'Denmark', 'flag' => 'flags/denmark.svg'],
        ['code' => 'DJ', 'name' => 'Djibouti', 'flag' => 'flags/djibouti.svg'],
        ['code' => 'DM', 'name' => 'Dominica', 'flag' => 'flags/dominica.svg'],
        ['code' => 'DO', 'name' => 'Dominican Republic', 'flag' => 'flags/dominican-republic.svg'],
        ['code' => 'EC', 'name' => 'Ecuador', 'flag' => 'flags/ecuador.svg'],
        ['code' => 'EG', 'name' => 'Egypt', 'flag' => 'flags/egypt.svg'],
        ['code' => 'SV', 'name' => 'El Salvador', 'flag' => 'flags/el-salvador.svg'],
        ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'flag' => 'flags/equatorial-guinea.svg'],
        ['code' => 'ER', 'name' => 'Eritrea', 'flag' => 'flags/eritrea.svg'],
        ['code' => 'EE', 'name' => 'Estonia', 'flag' => 'flags/estonia.svg'],
        ['code' => 'ET', 'name' => 'Ethiopia', 'flag' => 'flags/ethiopia.svg'],
        ['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'flag' => 'flags/falkland-islands.svg'],
        ['code' => 'FJ', 'name' => 'Fiji', 'flag' => 'flags/fiji.svg'],
        ['code' => 'FI', 'name' => 'Finland', 'flag' => 'flags/finland.svg'],
        ['code' => 'FR', 'name' => 'France', 'flag' => 'flags/france.svg'],
        ['code' => 'PF', 'name' => 'French Polynesia', 'flag' => 'flags/french-polynesia.svg'],
        ['code' => 'GA', 'name' => 'Gabon', 'flag' => 'flags/gabon.svg'],
        ['code' => 'GM', 'name' => 'Gambia', 'flag' => 'flags/gambia.svg'],
        ['code' => 'GE', 'name' => 'Georgia', 'flag' => 'flags/georgia.svg'],
        ['code' => 'DE', 'name' => 'Germany', 'flag' => 'flags/germany.svg'],
        ['code' => 'GH', 'name' => 'Ghana', 'flag' => 'flags/ghana.svg'],
        ['code' => 'GI', 'name' => 'Gibraltar', 'flag' => 'flags/gibraltar.svg'],
        ['code' => 'GR', 'name' => 'Greece', 'flag' => 'flags/greece.svg'],
        ['code' => 'GL', 'name' => 'Greenland', 'flag' => 'flags/greenland.svg'],
        ['code' => 'GD', 'name' => 'Grenada', 'flag' => 'flags/grenada.svg'],
        ['code' => 'GU', 'name' => 'Guam', 'flag' => 'flags/guam.svg'],
        ['code' => 'GT', 'name' => 'Guatemala', 'flag' => 'flags/guatemala.svg'],
        ['code' => 'GG', 'name' => 'Guernsey', 'flag' => 'flags/guernsey.svg'],
        ['code' => 'GN', 'name' => 'Guinea', 'flag' => 'flags/guinea.svg'],
        ['code' => 'GW', 'name' => 'Guinea-Bissau', 'flag' => 'flags/guinea-bissau.svg'],
        ['code' => 'HT', 'name' => 'Haiti', 'flag' => 'flags/haiti.svg'],
        ['code' => 'VA', 'name' => 'Holy See (Vatican City State)', 'flag' => 'flags/vatican-city.svg'],
        ['code' => 'HN', 'name' => 'Honduras', 'flag' => 'flags/honduras.svg'],
        ['code' => 'HK', 'name' => 'Hong Kong', 'flag' => 'flags/hong-kong.svg'],
        ['code' => 'HU', 'name' => 'Hungary', 'flag' => 'flags/hungary.svg'],
        ['code' => 'IS', 'name' => 'Iceland', 'flag' => 'flags/iceland.svg'],
        ['code' => 'IN', 'name' => 'India', 'flag' => 'flags/india.svg'],
        ['code' => 'ID', 'name' => 'Indonesia', 'flag' => 'flags/indonesia.svg'],
        ['code' => 'IR', 'name' => 'Iran, Islamic Republic of', 'flag' => 'flags/iran.svg'],
        ['code' => 'IQ', 'name' => 'Iraq', 'flag' => 'flags/iraq.svg'],
        ['code' => 'IE', 'name' => 'Ireland', 'flag' => 'flags/ireland.svg'],
        ['code' => 'IM', 'name' => 'Isle of Man', 'flag' => 'flags/isle-of-man.svg'],
        ['code' => 'IL', 'name' => 'Israel', 'flag' => 'flags/israel.svg'],
        ['code' => 'IT', 'name' => 'Italy', 'flag' => 'flags/italy.svg'],
        ['code' => 'JM', 'name' => 'Jamaica', 'flag' => 'flags/jamaica.svg'],
        ['code' => 'JP', 'name' => 'Japan', 'flag' => 'flags/japan.svg'],
        ['code' => 'JE', 'name' => 'Jersey', 'flag' => 'flags/jersey.svg'],
        ['code' => 'JO', 'name' => 'Jordan', 'flag' => 'flags/jordan.svg'],
        ['code' => 'KZ', 'name' => 'Kazakhstan', 'flag' => 'flags/kazakhstan.svg'],
        ['code' => 'KE', 'name' => 'Kenya', 'flag' => 'flags/kenya.svg'],
        ['code' => 'KI', 'name' => 'Kiribati', 'flag' => 'flags/kiribati.svg'],
        ['code' => 'KP', 'name' => "Korea, Democratic People's Republic of", 'flag' => 'flags/north-korea.svg'],
        ['code' => 'KW', 'name' => 'Kuwait', 'flag' => 'flags/kuwait.svg'],
        ['code' => 'KG', 'name' => 'Kyrgyzstan', 'flag' => 'flags/kyrgyzstan.svg'],
        ['code' => 'LA', 'name' => "Lao People's Democratic Republic", 'flag' => 'flags/laos.svg'],
        ['code' => 'LV', 'name' => 'Latvia', 'flag' => 'flags/latvia.svg'],
        ['code' => 'LB', 'name' => 'Lebanon', 'flag' => 'flags/lebanon.svg'],
        ['code' => 'LS', 'name' => 'Lesotho', 'flag' => 'flags/lesotho.svg'],
        ['code' => 'LR', 'name' => 'Liberia', 'flag' => 'flags/liberia.svg'],
        ['code' => 'LY', 'name' => 'Libya', 'flag' => 'flags/libya.svg'],
        ['code' => 'LI', 'name' => 'Liechtenstein', 'flag' => 'flags/liechtenstein.svg'],
        ['code' => 'LT', 'name' => 'Lithuania', 'flag' => 'flags/lithuania.svg'],
        ['code' => 'LU', 'name' => 'Luxembourg', 'flag' => 'flags/luxembourg.svg'],
        ['code' => 'MO', 'name' => 'Macao', 'flag' => 'flags/macao.svg'],
        ['code' => 'MG', 'name' => 'Madagascar', 'flag' => 'flags/madagascar.svg'],
        ['code' => 'MW', 'name' => 'Malawi', 'flag' => 'flags/malawi.svg'],
        ['code' => 'MY', 'name' => 'Malaysia', 'flag' => 'flags/malaysia.svg'],
        ['code' => 'MV', 'name' => 'Maldives', 'flag' => 'flags/maldives.svg'],
        ['code' => 'ML', 'name' => 'Mali', 'flag' => 'flags/mali.svg'],
        ['code' => 'MT', 'name' => 'Malta', 'flag' => 'flags/malta.svg'],
        ['code' => 'MH', 'name' => 'Marshall Islands', 'flag' => 'flags/marshall-island.svg'],
        ['code' => 'MQ', 'name' => 'Martinique', 'flag' => 'flags/martinique.svg'],
        ['code' => 'MR', 'name' => 'Mauritania', 'flag' => 'flags/mauritania.svg'],
        ['code' => 'MU', 'name' => 'Mauritius', 'flag' => 'flags/mauritius.svg'],
        ['code' => 'MX', 'name' => 'Mexico', 'flag' => 'flags/mexico.svg'],
        ['code' => 'FM', 'name' => 'Micronesia, Federated States of', 'flag' => 'flags/micronesia.svg'],
        ['code' => 'MD', 'name' => 'Moldova, Republic of', 'flag' => 'flags/moldova.svg'],
        ['code' => 'MC', 'name' => 'Monaco', 'flag' => 'flags/monaco.svg'],
        ['code' => 'MN', 'name' => 'Mongolia', 'flag' => 'flags/mongolia.svg'],
        ['code' => 'ME', 'name' => 'Montenegro', 'flag' => 'flags/montenegro.svg'],
        ['code' => 'MS', 'name' => 'Montserrat', 'flag' => 'flags/montserrat.svg'],
        ['code' => 'MA', 'name' => 'Morocco', 'flag' => 'flags/morocco.svg'],
        ['code' => 'MZ', 'name' => 'Mozambique', 'flag' => 'flags/mozambique.svg'],
        ['code' => 'MM', 'name' => 'Myanmar', 'flag' => 'flags/myanmar.svg'],
        ['code' => 'NA', 'name' => 'Namibia', 'flag' => 'flags/namibia.svg'],
        ['code' => 'NR', 'name' => 'Nauru', 'flag' => 'flags/nauru.svg'],
        ['code' => 'NP', 'name' => 'Nepal', 'flag' => 'flags/nepal.svg'],
        ['code' => 'NL', 'name' => 'Netherlands', 'flag' => 'flags/netherlands.svg'],
        ['code' => 'NZ', 'name' => 'New Zealand', 'flag' => 'flags/new-zealand.svg'],
        ['code' => 'NI', 'name' => 'Nicaragua', 'flag' => 'flags/nicaragua.svg'],
        ['code' => 'NE', 'name' => 'Niger', 'flag' => 'flags/niger.svg'],
        ['code' => 'NG', 'name' => 'Nigeria', 'flag' => 'flags/nigeria.svg'],
        ['code' => 'NU', 'name' => 'Niue', 'flag' => 'flags/niue.svg'],
        ['code' => 'NF', 'name' => 'Norfolk Island', 'flag' => 'flags/norfolk-island.svg'],
        ['code' => 'KP', 'name' => "North Korea", 'flag' => 'flags/north-korea.svg'],
        ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'flag' => 'flags/northern-mariana-islands.svg'],
        ['code' => 'NO', 'name' => 'Norway', 'flag' => 'flags/norway.svg'],
        ['code' => 'OM', 'name' => 'Oman', 'flag' => 'flags/oman.svg'],
        ['code' => 'PK', 'name' => 'Pakistan', 'flag' => 'flags/pakistan.svg'],
        ['code' => 'PW', 'name' => 'Palau', 'flag' => 'flags/palau.svg'],
        ['code' => 'PS', 'name' => 'Palestine, State of', 'flag' => 'flags/palestine.svg'],
        ['code' => 'PA', 'name' => 'Panama', 'flag' => 'flags/panama.svg'],
        ['code' => 'PG', 'name' => 'Papua New Guinea', 'flag' => 'flags/papua-new-guinea.svg'],
        ['code' => 'PY', 'name' => 'Paraguay', 'flag' => 'flags/paraguay.svg'],
        ['code' => 'PE', 'name' => 'Peru', 'flag' => 'flags/peru.svg'],
        ['code' => 'PH', 'name' => 'Philippines', 'flag' => 'flags/philippines.svg'],
        ['code' => 'PL', 'name' => 'Poland', 'flag' => 'flags/poland.svg'],
        ['code' => 'PT', 'name' => 'Portugal', 'flag' => 'flags/portugal.svg'],
        ['code' => 'PR', 'name' => 'Puerto Rico', 'flag' => 'flags/puerto-rico.svg'],
        ['code' => 'QA', 'name' => 'Qatar', 'flag' => 'flags/qatar.svg'],
        ['code' => 'RE', 'name' => 'Réunion', 'flag' => 'flags/reunion.svg'],
        ['code' => 'RO', 'name' => 'Romania', 'flag' => 'flags/romania.svg'],
        ['code' => 'RU', 'name' => 'Russian Federation', 'flag' => 'flags/russia.svg'],
        ['code' => 'RW', 'name' => 'Rwanda', 'flag' => 'flags/rwanda.svg'],
        ['code' => 'BL', 'name' => 'Saint Barthélemy', 'flag' => 'flags/saint-barthelemy.svg'],
        ['code' => 'SH', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'flag' => 'flags/saint-helena.svg'],
        ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'flag' => 'flags/saint-kitts-and-nevis.svg'],
        ['code' => 'LC', 'name' => 'Saint Lucia', 'flag' => 'flags/saint-lucia.svg'],
        ['code' => 'MF', 'name' => 'Saint Martin (French part)', 'flag' => 'flags/saint-martin.svg'],
        ['code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'flag' => 'flags/saint-pierre-and-miquelon.svg'],
        ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'flag' => 'flags/saint-vincent-and-the-grenadines.svg'],
        ['code' => 'WS', 'name' => 'Samoa', 'flag' => 'flags/samoa.svg'],
        ['code' => 'SM', 'name' => 'San Marino', 'flag' => 'flags/san-marino.svg'],
        ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'flag' => 'flags/sao-tome-and-principe.svg'],
        ['code' => 'SA', 'name' => 'Saudi Arabia', 'flag' => 'flags/saudi-arabia.svg'],
        ['code' => 'SN', 'name' => 'Senegal', 'flag' => 'flags/senegal.svg'],
        ['code' => 'RS', 'name' => 'Serbia', 'flag' => 'flags/serbia.svg'],
        ['code' => 'SC', 'name' => 'Seychelles', 'flag' => 'flags/seychelles.svg'],
        ['code' => 'SL', 'name' => 'Sierra Leone', 'flag' => 'flags/sierra-leone.svg'],
        ['code' => 'SG', 'name' => 'Singapore', 'flag' => 'flags/singapore.svg'],
        ['code' => 'SX', 'name' => 'Sint Maarten (Dutch part)', 'flag' => 'flags/sint-maarten.svg'],
        ['code' => 'SK', 'name' => 'Slovakia', 'flag' => 'flags/slovakia.svg'],
        ['code' => 'SI', 'name' => 'Slovenia', 'flag' => 'flags/slovenia.svg'],
        ['code' => 'SB', 'name' => 'Solomon Islands', 'flag' => 'flags/solomon-islands.svg'],
        ['code' => 'SO', 'name' => 'Somalia', 'flag' => 'flags/somalia.svg'],
        ['code' => 'ZA', 'name' => 'South Africa', 'flag' => 'flags/south-africa.svg'],
        ['code' => 'KR', 'name' => 'South Korea', 'flag' => 'flags/south-korea.svg'],
        ['code' => 'SS', 'name' => 'South Sudan', 'flag' => 'flags/south-sudan.svg'],
        ['code' => 'ES', 'name' => 'Spain', 'flag' => 'flags/spain.svg'],
        ['code' => 'LK', 'name' => 'Sri Lanka', 'flag' => 'flags/sri-lanka.svg'],
        ['code' => 'SD', 'name' => 'Sudan', 'flag' => 'flags/sudan.svg'],
        ['code' => 'SR', 'name' => 'Suriname', 'flag' => 'flags/suriname.svg'],
        ['code' => 'SZ', 'name' => 'Swaziland', 'flag' => 'flags/swaziland.svg'],
        ['code' => 'SE', 'name' => 'Sweden', 'flag' => 'flags/sweden.svg'],
        ['code' => 'CH', 'name' => 'Switzerland', 'flag' => 'flags/switzerland.svg'],
        ['code' => 'SY', 'name' => 'Syrian Arab Republic', 'flag' => 'flags/syria.svg'],
        ['code' => 'TW', 'name' => 'Taiwan, Province of China', 'flag' => 'flags/taiwan.svg'],
        ['code' => 'TJ', 'name' => 'Tajikistan', 'flag' => 'flags/tajikistan.svg'],
        ['code' => 'TZ', 'name' => 'Tanzania, United Republic of', 'flag' => 'flags/tanzania.svg'],
        ['code' => 'TH', 'name' => 'Thailand', 'flag' => 'flags/thailand.svg'],
        ['code' => 'TL', 'name' => 'Timor-Leste', 'flag' => 'flags/timor-leste.svg'],
        ['code' => 'TG', 'name' => 'Togo', 'flag' => 'flags/togo.svg'],
        ['code' => 'TK', 'name' => 'Tokelau', 'flag' => 'flags/tokelau.svg'],
        ['code' => 'TO', 'name' => 'Tonga', 'flag' => 'flags/tonga.svg'],
        ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'flag' => 'flags/trinidad-and-tobago.svg'],
        ['code' => 'TN', 'name' => 'Tunisia', 'flag' => 'flags/tunisia.svg'],
        ['code' => 'TR', 'name' => 'Turkey', 'flag' => 'flags/turkey.svg'],
        ['code' => 'TM', 'name' => 'Turkmenistan', 'flag' => 'flags/turkmenistan.svg'],
        ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'flag' => 'flags/turks-and-caicos-islands.svg'],
        ['code' => 'TV', 'name' => 'Tuvalu', 'flag' => 'flags/tuvalu.svg'],
        ['code' => 'UG', 'name' => 'Uganda', 'flag' => 'flags/uganda.svg'],
        ['code' => 'UA', 'name' => 'Ukraine', 'flag' => 'flags/ukraine.svg'],
        ['code' => 'AE', 'name' => 'United Arab Emirates', 'flag' => 'flags/united-arab-emirates.svg'],
        ['code' => 'GB', 'name' => 'United Kingdom', 'flag' => 'flags/united-kingdom.svg'],
        ['code' => 'US', 'name' => 'United States', 'flag' => 'flags/united-states.svg'],
        ['code' => 'UY', 'name' => 'Uruguay', 'flag' => 'flags/uruguay.svg'],
        ['code' => 'UZ', 'name' => 'Uzbekistan', 'flag' => 'flags/uzbekistan.svg'],
        ['code' => 'VU', 'name' => 'Vanuatu', 'flag' => 'flags/vanuatu.svg'],
        ['code' => 'VE', 'name' => 'Venezuela, Bolivarian Republic of', 'flag' => 'flags/venezuela.svg'],
        ['code' => 'VN', 'name' => 'Viet Nam', 'flag' => 'flags/vietnam.svg'],
        ['code' => 'VI', 'name' => 'Virgin Islands, U.S.', 'flag' => 'flags/virgin-islands.svg'],
        ['code' => 'WF', 'name' => 'Wallis and Futuna', 'flag' => 'flags/wallis-and-futuna.svg'],
        ['code' => 'EH', 'name' => 'Western Sahara', 'flag' => 'flags/western-sahara.svg'],
        ['code' => 'YE', 'name' => 'Yemen', 'flag' => 'flags/yemen.svg'],
        ['code' => 'ZM', 'name' => 'Zambia', 'flag' => 'flags/zambia.svg'],
        ['code' => 'ZW', 'name' => 'Zimbabwe', 'flag' => 'flags/zimbabwe.svg'],
    ];
}

function getCountryByCode($code = ''): ?array {
    if ($code) {
        $countries = getALLCountries();
        $code = strtoupper($code);

        foreach ($countries as $country) {
            if ($country['code'] === $code) {
                return $country;
            }
        }
    }
    return null;
}
        
